version: '3'
services:
  app-server:
    build: ./app-server
    depends_on: 
      - db
      - identity
    environment:
      - databaseURI=mongodb://db/prayer-board
      - identityServiceBaseUrl=http://identity:8081
    ports: 
      - "8080:8080"

  db:
    image: mongo
    ports:
      - "27017:27017"

  identity:
    build: ./identity-service
    depends_on:
      - db
    environment:
      - databaseURI=mongodb://db/identity
